---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  galaxy: requirements.yml
  python:
    ##################################
    # AWS
    - boto3>=1.26.0
    - botocore>=1.29.0
    ##################################
    # GCP
    - google-auth
    - requests
    ##################################
    # Azure ... see: https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt
    - packaging
    - requests[security]
    - xmltodict
    - msgraph-sdk==1.0.0
    - azure-cli-core==2.34.0
    - azure-common==1.1.11
    - azure-identity==1.14.0
    - azure-mgmt-authorization==2.0.0
    - azure-mgmt-apimanagement==3.0.0
    - azure-mgmt-batch==16.2.0
    - azure-mgmt-cdn==11.0.0
    - azure-mgmt-compute==26.1.0
    - azure-mgmt-containerinstance==9.0.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-containerregistry==9.1.0
    - azure-containerregistry==1.1.0
    - azure-mgmt-containerservice==20.0.0
    - azure-mgmt-datalake-store==1.0.0
    - azure-mgmt-datafactory==2.0.0
    - azure-mgmt-dns==8.0.0
    - azure-mgmt-marketplaceordering==1.1.0
    - azure-mgmt-monitor==3.0.0
    - azure-mgmt-managedservices==6.0.0
    - azure-mgmt-managementgroups==1.0.0
    - azure-mgmt-network==19.1.0
    - azure-mgmt-nspkg==2.0.0
    - azure-mgmt-privatedns==1.0.0
    - azure-mgmt-redis==13.0.0
    - azure-mgmt-resource==21.1.0
    - azure-mgmt-rdbms==10.0.0
    - azure-mgmt-search==8.0.0
    - azure-mgmt-servicebus==7.1.0
    - azure-mgmt-sql==3.0.1
    - azure-mgmt-storage==19.0.0
    - azure-mgmt-trafficmanager==1.0.0b1
    - azure-mgmt-web==6.1.0
    - azure-nspkg==2.0.0
    - azure-storage-blob==12.11.0
    - azure-core==1.28.0
    - azure-keyvault==4.2.0
    - azure-mgmt-keyvault==10.0.0
    - azure-mgmt-cosmosdb==6.4.0
    - azure-mgmt-hdinsight==9.0.0
    - azure-mgmt-devtestlabs==9.0.0
    - azure-mgmt-loganalytics==12.0.0
    - azure-mgmt-automation==1.0.0
    - azure-mgmt-iothub==2.2.0
    - azure-iot-hub==2.6.1
    - azure-mgmt-recoveryservices==2.0.0
    - azure-mgmt-recoveryservicesbackup==3.0.0
    - azure-mgmt-notificationhubs==7.0.0
    - azure-mgmt-eventhub==10.1.0

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

additional_build_files: []
    # - src: files/ansible.cfg
    #   dest: configs
    # - src: ../secrets/aap-demo-415618-8d416d08d099.json
    #   dest: configs

additional_build_steps:
  # prepend_galaxy:
  #   - ADD _build/configs/ansible.cfg ~/.ansible.cfg
  # prepend_base:
  #   - ADD _build/configs/aap-demo-415618-8d416d08d099.json /tmp/

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc